import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { Bell, Stethoscope } from "lucide-react";
import { UserNav } from "@/components/user-nav";
import { SiteNav } from "@/components/site-nav";
import { ReactNode } from "react";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, "antialiased bg-slate-50 text-slate-900")}> 
        <header className="sticky top-0 z-30 w-full border-b border-slate-200 bg-white/85 backdrop-blur supports-[backdrop-filter]:bg-white/70">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2 font-semibold text-slate-900">
              <Stethoscope className="h-6 w-6 text-[var(--accent)]" />
              <span>Healthcare Eclipse</span>
            </Link>
            <SiteNav />
            <div className="flex items-center gap-3">
              <button aria-label="Notifications" className="p-2 rounded-full hover:bg-slate-100">
                <Bell className="h-5 w-5" />
              </button>
              <UserNav />
            </div>
          </div>
        </header>
        <Providers>
          <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
            {children}
          </main>
        </Providers>
        <footer className="mt-10 border-t border-slate-200 bg-[#0b0b0c]">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12 grid gap-8 md:grid-cols-3 text-sm">
            <div>
              <div className="font-semibold text-white">Healthcare Eclipse</div>
              <p className="mt-2 text-slate-400">Detect silent diseases early with trustworthy AI insights.</p>
            </div>
            <div className="grid grid-cols-2 gap-3 text-slate-400">
              <Link href="/client" className="hover:text-white">Client App</Link>
              <Link href="/analyst" className="hover:text-white">Doctor Dashboard</Link>
              <Link href="/detective" className="hover:text-white">AI Insights</Link>
              <Link href="/admin" className="hover:text-white">Analytics</Link>
              <Link href="/surveys" className="hover:text-white">Surveys</Link>
              <Link href="#" className="hover:text-white">Privacy</Link>
            </div>
            <div className="md:text-right text-slate-400">© 2025 Healthcare Eclipse • All rights reserved</div>
          </div>
          <div className="border-t border-white/10">
            <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between text-xs text-slate-500">
              <span>Built with Next.js • TypeScript • Tailwind</span>
              <span className="text-[var(--accent)]">Healthy minds, healthy code.</span>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
