import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { Bell, Stethoscope } from "lucide-react";
import { UserNav } from "@/components/user-nav";
import { SiteNav } from "@/components/site-nav";
import { ReactNode } from "react";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, "antialiased bg-[var(--background)] text-[var(--foreground)]")}> 
        <header className="sticky top-0 z-30 w-full border-b border-[var(--card-border)] bg-[var(--background)]/95 backdrop-blur-md supports-[backdrop-filter]:bg-[var(--background)]/90 shadow-sm">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-3 font-semibold text-[var(--foreground)] group">
              <div className="rounded-lg bg-[var(--accent)] p-2 group-hover:bg-[var(--accent-hover)] transition-colors duration-200">
                <Stethoscope className="h-5 w-5 text-white" />
              </div>
              <span className="text-lg gradient-text professional-heading">Healthcare Eclipse</span>
            </Link>
            <SiteNav />
            <div className="flex items-center gap-3">
              <button aria-label="Notifications" className="p-2 rounded-md hover:bg-[var(--accent-bg)] transition-colors duration-200">
                <Bell className="h-4 w-4 text-[var(--foreground-muted)] hover:text-[var(--accent)]" />
              </button>
              <div className="min-w-[80px]">
                <UserNav />
              </div>
            </div>
          </div>
        </header>
        <Providers>
          <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
            {children}
          </main>
        </Providers>
        <footer className="mt-16 border-t border-gray-200 bg-gray-100">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12 grid gap-8 md:grid-cols-3 text-sm">
            <div>
              <div className="font-semibold text-gray-900 gradient-text text-lg professional-heading">Healthcare Eclipse</div>
              <p className="mt-3 text-gray-700 leading-relaxed professional-text">Detect silent diseases early with trustworthy AI insights and advanced health monitoring.</p>
            </div>
            <div className="grid grid-cols-2 gap-3 text-gray-700">
              <Link href="/client" className="hover:text-[var(--accent)] transition-colors duration-200 professional-text">Client App</Link>
              <Link href="/analyst" className="hover:text-[var(--accent)] transition-colors duration-200 professional-text">Analyst</Link>
              <Link href="/detective" className="hover:text-[var(--accent)] transition-colors duration-200 professional-text">AI Insights</Link>
              <Link href="/admin" className="hover:text-[var(--accent)] transition-colors duration-200 professional-text">Analytics</Link>
              <Link href="/login" className="hover:text-[var(--accent)] transition-colors duration-200 professional-text">Login</Link>
              <Link href="/register" className="hover:text-[var(--accent)] transition-colors duration-200 professional-text">Register</Link>
            </div>
            <div className="md:text-right text-gray-700">
              <div className="font-medium text-gray-900 mb-2 professional-heading">© 2025 Healthcare Eclipse</div>
              <div className="professional-text">All rights reserved</div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
